Add files via upload

diff --git a/other/aria2_debian b/other/aria2_debian
--- a/other/aria2_debian
+++ b/other/aria2_debian
@@ -18,8 +18,8 @@ CONFIG="/root/.aria2/aria2.conf"
 LOG="/root/.aria2/aria2.log"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
-Info="${Green_font_prefix}[信息]${Font_color_suffix}"
-Error="${Red_font_prefix}[错误]${Font_color_suffix}"
+Info="${Green_font_prefix}[訊息]${Font_color_suffix}"
+Error="${Red_font_prefix}[錯誤]${Font_color_suffix}"
 RETVAL=0
 
 check_running(){
@@ -31,7 +31,7 @@ check_running(){
 	fi
 }
 Read_config(){
-	[[ ! -e ${CONFIG} ]] && echo -e "${Error} ${NAME} 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONFIG} ]] && echo -e "${Error} ${NAME} 設定檔案不存在 !" && exit 1
 	Download_dir=$(cat ${CONFIG}|grep -v '#'|grep "dir=")
 	[[ ! -z "${Download_dir}" ]] && Download_dir=$(echo "${Download_dir}"|awk -F '=' '{print $2}')
 	RPC_listen_port=$(cat ${CONFIG}|grep -v '#'|grep "rpc-listen-port=")
@@ -47,33 +47,33 @@ View_Config(){
 		if [[ -z "${ip}" ]]; then
 			ip=$(wget -qO- -t1 -T2 members.3322.org/dyndns/getip)
 			if [[ -z "${ip}" ]]; then
-				ip="VPS_IP(外网IP检测失败)"
+				ip="VPS_IP(外網IP檢測失敗)"
 			fi
 		fi
 	fi
 	[[ -z "${Download_dir}" ]] && Download_dir="/usr/local/aria2/"
 	[[ -z "${RPC_listen_port}" ]] && RPC_listen_port="6800"
-	[[ -z "${RPC_secret}" ]] && RPC_secret="无令牌密码"
+	[[ -z "${RPC_secret}" ]] && RPC_secret="無令牌密碼"
 	clear
-	echo -e "\nAria2 简单配置信息：\n
+	echo -e "\nAria2 簡單設定訊息：\n
  地址\t: ${Green_font_prefix}${ip}${Font_color_suffix}
- 端口\t: ${Green_font_prefix}${RPC_listen_port}${Font_color_suffix}
- 密码\t: ${Green_font_prefix}${RPC_secret}${Font_color_suffix}
- 目录\t: ${Green_font_prefix}${Download_dir}${Font_color_suffix}\n"
+ 埠\t: ${Green_font_prefix}${RPC_listen_port}${Font_color_suffix}
+ 密碼\t: ${Green_font_prefix}${RPC_secret}${Font_color_suffix}
+ 目錄\t: ${Green_font_prefix}${Download_dir}${Font_color_suffix}\n"
 }
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info} $NAME (PID ${PID}) 正在執行..." && exit 0
 	else
 		nohup aria2c -c "${CONFIG}" > "${LOG}" 2>&1 &
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
 			View_Config
-			echo -e "${Info} $NAME 启动成功 !"
+			echo -e "${Info} $NAME 啟動成功 !"
 		else
-			echo -e "${Error} $NAME 启动失败 !"
+			echo -e "${Error} $NAME 啟動失敗 !"
 		fi
 	fi
 }
@@ -85,10 +85,10 @@ do_stop(){
 		if [[ $RETVAL -eq 0 ]]; then
 			echo -e "${Info} $NAME 停止成功 !"
 		else
-			echo -e "${Error} $NAME 停止失败 !"
+			echo -e "${Error} $NAME 停止失敗 !"
 		fi
 	else
-		echo -e "${Info} $NAME 未运行"
+		echo -e "${Info} $NAME 未執行"
 		RETVAL=1
 	fi
 }
@@ -96,9 +96,9 @@ do_status(){
 	check_running
 	if [[ $? -eq 0 ]]; then
 		View_Config
-		echo -e "${Info} $NAME (PID $(echo ${PID})) 正在运行..."
+		echo -e "${Info} $NAME (PID $(echo ${PID})) 正在執行..."
 	else
-		echo -e "${Info} $NAME 未运行 !"
+		echo -e "${Info} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
diff --git a/other/brook-pf_debian b/other/brook-pf_debian
--- a/other/brook-pf_debian
+++ b/other/brook-pf_debian
@@ -17,8 +17,8 @@ CONF="${FILE}/brook.conf"
 LOG="${FILE}/brook.log"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
-Info="${Green_font_prefix}[信息]${Font_color_suffix}"
-Error="${Red_font_prefix}[错误]${Font_color_suffix}"
+Info="${Green_font_prefix}[訊息]${Font_color_suffix}"
+Error="${Red_font_prefix}[錯誤]${Font_color_suffix}"
 RETVAL=0
 
 check_running(){
@@ -30,10 +30,10 @@ check_running(){
 	fi
 }
 read_config(){
-	[[ ! -e ${CONF} ]] && echo -e "${Error} Brook 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONF} ]] && echo -e "${Error} Brook 設定檔案不存在 !" && exit 1
 	user_all=$(cat ${CONF}|sed '/^\s*$/d')
 	user_all_num=$(echo "${user_all}"|wc -l)
-	[[ -z ${user_all} ]] && echo -e "${Error} Brook 配置文件中用户配置为空 !" && exit 1
+	[[ -z ${user_all} ]] && echo -e "${Error} Brook 設定檔案中使用者設定為空 !" && exit 1
 }
 View_User(){
 	for((integer = 1; integer <= ${user_all_num}; integer++))
@@ -45,9 +45,9 @@ View_User(){
 		if [[ ${user_Enabled_pf} == "0" ]]; then
 				user_Enabled_pf_1="${Red_font_prefix}禁用${Font_color_suffix}"
 			else
-				user_Enabled_pf_1="${Green_font_prefix}启用${Font_color_suffix}"
+				user_Enabled_pf_1="${Green_font_prefix}啟用${Font_color_suffix}"
 		fi
-		user_list_all=${user_list_all}"本地监听端口: ${Green_font_prefix}"${user_port}"${Font_color_suffix}\t 被转发IP: ${Green_font_prefix}"${user_ip_pf}"${Font_color_suffix}\t 被转发端口: ${Green_font_prefix}"${user_port_pf}"${Font_color_suffix}\t 状态: ${user_Enabled_pf_1}\n"
+		user_list_all=${user_list_all}"本機監聽埠: ${Green_font_prefix}"${user_port}"${Font_color_suffix}\t 被轉發IP: ${Green_font_prefix}"${user_ip_pf}"${Font_color_suffix}\t 被轉發埠: ${Green_font_prefix}"${user_port_pf}"${Font_color_suffix}\t 狀態: ${user_Enabled_pf_1}\n"
 		user_IP=""
 	done
 	ip=$(wget -qO- -t1 -T2 ipinfo.io/ip)
@@ -60,18 +60,18 @@ View_User(){
 			fi
 		fi
 	fi
-	echo -e "当前端口转发总数: ${Green_background_prefix} "${user_all_num}" ${Font_color_suffix} 当前服务器IP: ${Green_background_prefix} "${ip}" ${Font_color_suffix}"
+	echo -e "目前埠轉發總數: ${Green_background_prefix} "${user_all_num}" ${Font_color_suffix} 目前伺服器IP: ${Green_background_prefix} "${ip}" ${Font_color_suffix}"
 	echo -e "${user_list_all}"
 	echo -e "========================\n"
 }
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} ${NAME} (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info} ${NAME} (PID ${PID}) 正在執行..." && exit 0
 	else
 		read_config
 		cd ${FILE}
-		echo -e "${Info} ${NAME} 启动中..."
+		echo -e "${Info} ${NAME} 啟動中..."
 		servers_all=""
 		for((integer = 1; integer <= ${user_all_num}; integer++))
 		do
@@ -88,10 +88,10 @@ do_start(){
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
-			echo -e "${Info} ${NAME} 启动成功 !"
+			echo -e "${Info} ${NAME} 啟動成功 !"
 			View_User
 		else
-			echo -e "${Error} ${NAME} 启动失败 !"
+			echo -e "${Error} ${NAME} 啟動失敗 !"
 		fi
 	fi
 }
@@ -103,10 +103,10 @@ do_stop(){
 		if [[ $RETVAL -eq 0 ]]; then
 			echo -e "${Info} ${NAME} 停止成功 !"
 		else
-			echo -e "${Error} ${NAME} 停止失败 !"
+			echo -e "${Error} ${NAME} 停止失敗 !"
 		fi
 	else
-		echo -e "${Info} ${NAME} 未运行"
+		echo -e "${Info} ${NAME} 未執行"
 		RETVAL=1
 	fi
 }
@@ -115,9 +115,9 @@ do_status(){
 	if [[ $? -eq 0 ]]; then
 		read_config
 		View_User
-		echo -e "${Info} ${NAME} (PID ${PID}) 正在运行..."
+		echo -e "${Info} ${NAME} (PID ${PID}) 正在執行..."
 	else
-		echo -e "${Info} ${NAME} 未运行 !"
+		echo -e "${Info} ${NAME} 未執行 !"
 		RETVAL=1
 	fi
 }
diff --git a/other/brook_centos b/other/brook_centos
--- a/other/brook_centos
+++ b/other/brook_centos
@@ -19,8 +19,8 @@ CONF="/usr/local/brook/brook.conf"
 LOG="/usr/local/brook/brook.log"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
-Info="${Green_font_prefix}[信息]${Font_color_suffix}"
-Error="${Red_font_prefix}[错误]${Font_color_suffix}"
+Info="${Green_font_prefix}[訊息]${Font_color_suffix}"
+Error="${Red_font_prefix}[錯誤]${Font_color_suffix}"
 RETVAL=0
 
 check_running(){
@@ -32,20 +32,20 @@ check_running(){
 	fi
 }
 read_config(){
-	[[ ! -e ${CONF} ]] && echo -e "${Error} Brook 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONF} ]] && echo -e "${Error} Brook 設定檔案不存在 !" && exit 1
 	user_all=$(cat ${CONF}|sed "1d")
 	user_all_num=$(echo "${user_all}"|wc -l)
-	[[ -z ${user_all} ]] && echo -e "${Error} Brook 配置文件中用户配置为空 !" && exit 1
+	[[ -z ${user_all} ]] && echo -e "${Error} Brook 設定檔案中使用者設定為空 !" && exit 1
 	protocol=$(cat ${CONF}|sed -n "1p")
 }
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info} $NAME (PID ${PID}) 正在執行..." && exit 0
 	else
 		read_config
 		cd ${FILE}
-		echo -e "${Info} $NAME 启动中..."
+		echo -e "${Info} $NAME 啟動中..."
 		servers_all=""
 		for((integer = 1; integer <= ${user_all_num}; integer++))
 		do
@@ -58,9 +58,9 @@ do_start(){
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
-			echo -e "${Info} $NAME 启动成功 !"
+			echo -e "${Info} $NAME 啟動成功 !"
 		else
-			echo -e "${Error} $NAME 启动失败 !"
+			echo -e "${Error} $NAME 啟動失敗 !"
 		fi
 	fi
 }
@@ -72,19 +72,19 @@ do_stop(){
 		if [[ $RETVAL -eq 0 ]]; then
 			echo -e "${Info} $NAME 停止成功 !"
 		else
-			echo -e "${Error} $NAME 停止失败 !"
+			echo -e "${Error} $NAME 停止失敗 !"
 		fi
 	else
-		echo -e "${Info} $NAME 未运行"
+		echo -e "${Info} $NAME 未執行"
 		RETVAL=1
 	fi
 }
 do_status(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..."
+		echo -e "${Info} $NAME (PID ${PID}) 正在執行..."
 	else
-		echo -e "${Info} $NAME 未运行 !"
+		echo -e "${Info} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
diff --git a/other/cloudt_debian b/other/cloudt_debian
--- a/other/cloudt_debian
+++ b/other/cloudt_debian
@@ -19,8 +19,8 @@ CONF="${FILE}/cloud-torrent.conf"
 LOG="/tmp/ct.log"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
-Info="${Green_font_prefix}[信息]${Font_color_suffix}"
-Error="${Red_font_prefix}[错误]${Font_color_suffix}"
+Info="${Green_font_prefix}[訊息]${Font_color_suffix}"
+Error="${Red_font_prefix}[錯誤]${Font_color_suffix}"
 RETVAL=0
 
 check_running(){
@@ -32,7 +32,7 @@ check_running(){
 	fi
 }
 read_config(){
-	[[ ! -e ${CONF} ]] && echo -e "${Error} Cloud Torrent 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONF} ]] && echo -e "${Error} Cloud Torrent 設定檔案不存在 !" && exit 1
 	host=`cat ${CONF}|grep "host = "|awk -F "host = " '{print $NF}'`
 	port=`cat ${CONF}|grep "port = "|awk -F "port = " '{print $NF}'`
 	user=`cat ${CONF}|grep "user = "|awk -F "user = " '{print $NF}'`
@@ -58,26 +58,26 @@ View_User(){
 	fi
 	if [[ -z ${user} ]]; then
 		clear && echo "————————————————" && echo
-		echo -e " 你的 Cloud Torrent 信息 :" && echo
+		echo -e " 你的 Cloud Torrent 訊息 :" && echo
 		echo -e " 地址\t: ${Green_font_prefix}http://${host}${port}${Font_color_suffix}"
 		echo && echo "————————————————"
 	else
 		clear && echo "————————————————" && echo
-		echo -e " 你的 Cloud Torrent 信息 :" && echo
+		echo -e " 你的 Cloud Torrent 訊息 :" && echo
 		echo -e " 地址\t: ${Green_font_prefix}http://${host}${port}${Font_color_suffix}"
-		echo -e " 用户\t: ${Green_font_prefix}${user}${Font_color_suffix}"
-		echo -e " 密码\t: ${Green_font_prefix}${passwd}${Font_color_suffix}"
+		echo -e " 使用者\t: ${Green_font_prefix}${user}${Font_color_suffix}"
+		echo -e " 密碼\t: ${Green_font_prefix}${passwd}${Font_color_suffix}"
 		echo && echo "————————————————"
 	fi
 }
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info} $NAME (PID ${PID}) 正在執行..." && exit 0
 	else
 		read_config
 		cd ${FILE}
-		echo -e "${Info} $NAME 启动中..."
+		echo -e "${Info} $NAME 啟動中..."
 		if [[ -z ${user} ]]; then
 			./cloud-torrent -t "Cloud Torrent - DOUBI" -h "${host}" -p ${port} -l >> "${LOG}" 2>&1 &
 		else
@@ -86,10 +86,10 @@ do_start(){
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
-			echo -e "${Info} $NAME 启动成功 !"
+			echo -e "${Info} $NAME 啟動成功 !"
 			View_User
 		else
-			echo -e "${Error} $NAME 启动失败(请运行脚本查看日志错误输出) !"
+			echo -e "${Error} $NAME 啟動失敗(請執行腳本查看日誌錯誤輸出) !"
 		fi
 	fi
 }
@@ -101,10 +101,10 @@ do_stop(){
 		if [[ $RETVAL -eq 0 ]]; then
 			echo -e "${Info} $NAME 停止成功 !"
 		else
-			echo -e "${Error} $NAME 停止失败 !"
+			echo -e "${Error} $NAME 停止失敗 !"
 		fi
 	else
-		echo -e "${Info} $NAME 未运行"
+		echo -e "${Info} $NAME 未執行"
 		RETVAL=1
 	fi
 }
@@ -113,9 +113,9 @@ do_status(){
 	if [[ $? -eq 0 ]]; then
 		read_config
 		View_User
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..."
+		echo -e "${Info} $NAME (PID ${PID}) 正在執行..."
 	else
-		echo -e "${Info} $NAME 未运行 !"
+		echo -e "${Info} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
diff --git a/other/dowsdns_debian b/other/dowsdns_debian
--- a/other/dowsdns_debian
+++ b/other/dowsdns_debian
@@ -27,7 +27,7 @@ check_running(){
 	fi
 }
 Read_config(){
-	[[ ! -e ${CONF} ]] && echo -e "${Error} DowsDNS 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONF} ]] && echo -e "${Error} DowsDNS 設定檔案不存在 !" && exit 1
 	local_dns_port=`cat ${CONF}|grep "Local_dns_port"|sed -r 's/.*:(.+),.*/\1/'`
 }
 View_dowsdns(){
@@ -39,16 +39,16 @@ View_dowsdns(){
 		[[ -z ${ip} ]] && ip="VPS_IP"
 	fi
 	clear && echo "————————————————" && echo
-	echo -e " 请在你的设备中设置DNS服务器为：
- IP : ${Info_font_prefix}${ip}${Font_suffix} ,端口 : ${Info_font_prefix}${local_dns_port}${Font_suffix}
+	echo -e " 請在你的設備中設定DNS伺服器為：
+ IP : ${Info_font_prefix}${ip}${Font_suffix} ,埠 : ${Info_font_prefix}${local_dns_port}${Font_suffix}
  
- 注意：如果设备中没有 DNS端口设置选项，那么就只能使用默认的 53 端口"
+ 注意：如果設備中沒有 DNS埠設定選項，那麼就只能使用預設的 53 埠"
 	echo && echo "————————————————"
 }
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID $(echo ${PID})) 正在运行..." && exit 0
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME (PID $(echo ${PID})) 正在執行..." && exit 0
 	else
 		cd "${BIN}"
 		nohup python start.py > /tmp/dowsdns.log 2>&1 &
@@ -56,9 +56,9 @@ do_start(){
 		check_running
 		if [[ $? -eq 0 ]]; then
 			View_dowsdns
-			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 启动成功 !"
+			echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 啟動成功 !"
 		else
-			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 启动失败 !"
+			echo -e "${Error_font_prefix}[錯誤]${Font_suffix} $NAME 啟動失敗 !"
 		fi
 	fi
 }
@@ -68,12 +68,12 @@ do_stop(){
 		kill -9 ${PID}
 		RETVAL=$?
 		if [[ $RETVAL -eq 0 ]]; then
-			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 停止成功 !"
+			echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 停止成功 !"
 		else
-			echo -e "${Error_font_prefix}[错误]${Font_suffix}$NAME 停止失败 !"
+			echo -e "${Error_font_prefix}[錯誤]${Font_suffix}$NAME 停止失敗 !"
 		fi
 	else
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
@@ -81,9 +81,9 @@ do_status(){
 	check_running
 	if [[ $? -eq 0 ]]; then
 		View_dowsdns
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID $(echo ${PID})) 正在运行..."
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME (PID $(echo ${PID})) 正在執行..."
 	else
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
